import sys
import os
import re
import csv
import importlib
import argparse

importlib.reload(sys)

from pdfminer.pdfparser import PDFParser
from pdfminer.pdfdocument import PDFDocument
from pdfminer.pdfpage import PDFPage
from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
from pdfminer.converter import PDFPageAggregator
from pdfminer.layout import LTTextBoxHorizontal,LAParams
from pdfminer.pdfpage import PDFTextExtractionNotAllowed


COLLEGE_211 = ['北京大学',
 '中国人民大学',
 '清华大学',
 '北京交通大学',
 '北京工业大学',
 '北京航空航天大学',
 '北京理工大学',
 '北京科技大学',
 '北京化工大学',
 '北京邮电大学',
 '中国农业大学',
 '北京林业大学',
 '北京中医药大学',
 '北京师范大学',
 '北京外国语大学',
 '中国传媒大学',
 '中央财经大学',
 '对外经济贸易大学',
 '北京体育大学',
 '中央音乐学院',
 '中央民族大学',
 '中国政法大学',
 '华北电力大学',
 '南开大学',
 '天津大学',
 '天津医科大学',
 '河北工业大学',
 '太原理工大学',
 '内蒙古大学',
 '辽宁大学',
 '大连理工大学',
 '东北大学',
 '大连海事大学',
 '吉林大学',
 '延边大学',
 '东北师范大学',
 '哈尔滨工业大学',
 '哈尔滨工程大学',
 '东北农业大学',
 '东北林业大学',
 '复旦大学',
 '同济大学',
 '上海交通大学',
 '华东理工大学',
 '东华大学',
 '华东师范大学',
 '上海外国语大学',
 '上海财经大学',
 '上海大学',
 '第二军医大学 ',
 '南京大学',
 '苏州大学',
 '东南大学',
 '南京航空航天大学',
 '南京理工大学',
 '中国矿业大学',
 '河海大学',
 '江南大学',
 '南京农业大学',
 '中国药科大学',
 '南京师范大学',
 '浙江大学',
 '安徽大学',
 '中国科学技术大学',
 '合肥工业大学',
 '厦门大学',
 '福州大学',
 '南昌大学',
 '山东大学',
 '中国海洋大学',
 '中国石油大学',
 '郑州大学',
 '武汉大学',
 '华中科技大学',
 '中国地质大学',
 '武汉理工大学',
 '华中农业大学',
 '华中师范大学',
 '中南财经政法大学',
 '湖南大学',
 '中南大学',
 '湖南师范大学',
 '国防科学技术大学',
 '中山大学',
 '暨南大学',
 '华南理工大学',
 '华南师范大学',
 '广西大学',
 '海南大学',
 '四川大学',
 '西南交通大学',
 '电子科技大学',
 '四川农业大学',
 '西南财经大学',
 '重庆大学',
 '西南大学',
 '贵州大学',
 '云南大学',
 '西藏大学',
 '西北大学',
 '西安交通大学',
 '西北工业大学',
 '西安电子科技大学',
 '长安大学',
 '西北农林科技大学',
 '陕西师范大学',
 '第四军医大学',
 '兰州大学',
 '青海大学',
 '宁夏大学',
 '新疆大学',
 '石河子大学',
 '南方科技大学'
]

COLLEGE_QS = ['麻省理工学院',
 'Massachusetts Institute of Technology',
 '牛津大学',
 'Oxford university',
 '斯坦福大学',
 'Stanford University',
 '剑桥大学',
 'Cambridge University',
 '哈佛大学',
 'Harvard University',
 '加州理工大学（Caltech)',
 'California Institute of Technology (Caltech)',
 '帝国理工学院',
 'Imperial College',
 '苏黎世联邦理工大学（瑞士联邦理工学院）',
 'ETH Zurich (Swiss Federal Institute of Technology)',
 '伦敦大学学院',
 'University College London',
 '芝加哥大学',
 'University of Chicago',
 '新加坡国立大学',
 'National University of Singapore',
 '南洋理工大学',
 'Nanyang Technological University',
 '宾夕法尼亚大学',
 'University of Pennsylvania',
 '洛桑联邦理工学院（EPFL)',
 'Federal Institute of Technology Lausanne (EPFL)',
 '耶鲁大学',
 'Yale University',
 '爱丁堡大学',
 'University of Edinburgh',
 '清华大学',
 'Tsinghua University',
 '北京大学',
 'Beijing University',
 '哥伦比亚大学',
 'Columbia University',
 '普林斯顿大学',
 'Princeton University',
 '康奈尔大学',
 'Cornell University',
 '香港大学（HKU）',
 'The University of Hong Kong (HKU)',
 '东京大学',
 'University of Tokyo',
 '密歇根大学',
 'University of Michigan',
 '约翰霍普金斯大学',
 'Johns Hopkins University',
 '多伦多大学',
 'University of Toronto',
 '麦吉尔大学',
 'McGill University',
 '澳大利亚国立大学（ANU)',
 'Australian National University (ANU)',
 '曼彻斯特大学',
 'University of Manchester',
 '西北大学',
 'Northwest University',
 '复旦大学',
 'Fudan University',
 '加州大学伯克利分校',
 'University of California Berkeley',
 '京都大学',
 'Kyoto University',
 '香港科技大学（HKUST)',
 'Hong Kong University of Science and Technology (HKUST)',
 '伦敦国王学院',
 "King's College London",
 '首尔国立大学',
 'Seoul National University',
 '墨尔本大学',
 'University of Melbourne',
 '悉尼大学',
 'University of Sydney',
 '香港中文大学',
 'Chinese University of Hong Kong',
 '加州大学洛杉矶分校',
 'UCLA',
 '韩国科学技术研究所',
 'Korea Institute of Science and Technology',
 '纽约大学（NYU）',
 'New York University (NYU)',
 '新南威尔士大学（UNSW）',
 'University of New South Wales (UNSW)',
 '巴黎科学艺术人文大学',
 'Paris University of Sciences, Arts and Humanities',
 '浙江大学',
 'Zhejiang University',
 '不列颠哥伦比亚大学',
 'University of British Columbia',
 '昆士兰大学（UQ）',
 'University of Queensland (UQ)',
 '加州大学圣地亚哥分校',
 'University of California San Diego',
 '巴黎理工学院',
 'Paris Polytechnic',
 '伦敦经济政治学院',
 'London School of Economics and Political Science',
 '上海交通大学',
 'Shanghai Jiaotong University',
 '慕尼黑工业大学',
 'Munich Industrial University',
 '杜克大学',
 'Duke University',
 '卡内基梅隆大学',
 'Carnegie Mellon University',
 '香港城市大学',
 'City University of Hong Kong',
 '阿姆斯特丹大学',
 'University of Amsterdam',
 '东京工业大学',
 'Tokyo Institute of Technology',
 '代尔夫特理工大学',
 'Delft University of Technology',
 '蒙纳士大学',
 'Monash University',
 '布朗大学',
 'Brown University',
 '华威大学',
 'Warwick University',
 '布里斯托大学',
 'University of Bristol',
 '鲁普莱希特-卡尔斯-海德堡大学',
 'Ruprecht-Kars-Heidelberg University',
 '路德维希-马克西米利安-慕尼黑大学',
 'Ludwig Maximilian University of Munich',
 '马来亚大学（UM）',
 'University of Malaya (UM)',
 '香港理工大学',
 'Hong Kong Polytechnic University',
 '德克萨斯大学奥斯汀分校',
 'University of Texas at Austin',
 '台湾大学',
 'Taiwan University',
 '布宜诺斯艾利斯大学',
 'University of Buenos Aires',
 '鲁汶大学',
 'University of Leuven',
 '苏黎世大学',
 'University of Zurich',
 '索邦大学',
 'Sorbonne University',
 '格拉斯哥大学',
 'University of Glasgow',
 '高丽大学',
 'Korea University',
 '大阪大学',
 'Osaka University',
 '威斯康星大学麦迪逊分校',
 'University of Wisconsin-Madison',
 '南安普敦大学',
 'University of Southampton',
 '罗蒙诺索夫莫斯科国立大学',
 'Lomonosov Moscow State University',
 '哥本哈根大学',
 'University of Copenhagen',
 '延世大学',
 'Yonsei University',
 '浦项科技大学',
 'Pohang University of Science and Technology',
 '杜伦大学',
 'Durham University',
 '东北大学',
 'Northeastern University',
 '伊利诺伊大学香槟分校',
 'University of Illinois at Urbana-Champaign',
 '奥克兰大学',
 'University of Auckland',
 '华盛顿大学',
 'Washington University',
 '巴黎第十一大学',
 'Eleventh university of paris',
 '隆德大学',
 'Lund University',
 '乔治亚理工学院(GeorgiaTech)',
 'Georgia Institute of Technology (GeorgiaTech)',
 '皇家理工学院',
 'Royal Institute of Technology',
 '伯明翰大学',
 'University of Birmingham',
 '圣安德鲁斯大学',
 'University of St Andrews',
 '利兹大学',
 'University of Leeds',
 '西澳大学（UWA）',
 'University of Western Australia (UWA)',
 '赖斯大学',
 'Rice University',
 '谢菲尔德大学',
 'University of Sheffield',
 '宾夕法尼亚州立大学',
 'Pennsylvania State University',
 '成均馆大学',
 'Sungkyunkwan University',
 '中国科学技术大学',
 'University of Science and Technology of China',
 '丹麦技术大学',
 'Technical University of Denmark',
 '北卡罗来纳大学教堂山',
 'University of North Carolina at Chapel Hill',
 '都柏林三一学院',
 'Trinity College Dublin',
 '奥斯陆大学',
 'University of Oslo',
 '诺丁汉大学',
 'University of Nottingham',
 '赫尔辛基大学',
 'University of Helsinki',
 '墨西哥国立自治大学',
 'National Autonomous University of Mexico',
 '日内瓦大学',
 'University of Geneva',
 '华盛顿大学在圣路易斯',
 'Washington University in St. Louis',
 '阿德莱德大学',
 'University of Adelaide',
 '阿卜杜勒·阿齐兹国王大学（KAU）',
 'King Abdulaziz University (KAU)',
 '乌得勒支大学',
 'Utrecht University',
 '蒙特利尔大学',
 'University of Montreal',
 '阿尔托大学',
 'Aalto University',
 '波士顿大学',
 'Boston University',
 '莱顿大学',
 'Leiden University',
 '南加州大学',
 'University of Southern California',
 '普渡大学',
 'Purdue University',
 '伦敦大学皇后玛丽学院（QMUL）',
 'Queen Mary University of London (QMUL)',
 '名古屋大学',
 'Nagoya University',
 '伯尔尼大学',
 'University of Bern',
 '俄亥俄州立大学',
 'Ohio State University',
 '查尔姆斯理工大学',
 'Chalmers University of Technology',
 '圣保罗大学',
 'Sao Paulo University',
 '瓦赫宁根大学',
 'Wageningen University',
 '乌普萨拉大学',
 'Uppsala University',
 '埃因霍芬理工大学',
 'Eindhoven University of Technology',
 '阿尔伯塔大学',
 'University of Alberta',
 '柏林自由大学',
 'Free University of Berlin',
 '柏林洪堡大学',
 'Humboldt University of Berlin',
 '格罗宁根大学',
 'University of Groningen',
 '里昂高等师范学院',
 'Lyon Normal University',
 '南京大学',
 'Nanjing University',
 '兰卡斯特大学',
 'Lancaster University',
 '悉尼科技大学（UTS）',
 'University of Technology Sydney (UTS)',
 '纽卡斯尔大学',
 'Newcastle University',
 '智利天主教大学',
 'Catholic University of Chile',
 '卡尔斯鲁厄理工学院',
 'Karlsruhe Institute of Technology',
 '九州大学',
 'Kyushu University',
 '巴塞尔大学',
 'University of Basel',
 '加州大学戴维斯分校',
 'University of California Davis',
 '麦克马斯特大学',
 'McMaster University',
 '根特大学',
 'Ghent University',
 '米兰理工大学',
 'Politecnico di Milano',
 '马来西亚博特拉大学（UPM）',
 'University Putra Malaysia (UPM)',
 '马来西亚国民大学（UKM）',
 'National University of Malaysia (UKM)',
 '北海道大学',
 'Hokkaido University',
 '加州大学圣芭芭拉分校',
 'University of California Santa Barbara',
 '马来西亚理科大学（USM）',
 'University of Science Malaysia (USM)',
 '斯德哥尔摩大学',
 'Stockholm University',
 '埃克塞特大学',
 'University of Exeter',
 '滑铁卢大学',
 'University of Waterloo',
 '卡迪夫大学',
 'Cardiff University',
 '维也纳大学',
 'University of Vienna',
 '约克大学',
 'York University',
 '罗切斯特大学',
 'University of Rochester',
 '奥胡斯大学',
 'Aarhus University',
 '汉阳大学',
 'Hanyang University',
 '密歇根州立大学',
 'Michigan State University',
 '马里兰大学，学院公园',
 'University of Maryland, College Park',
 '柏林工业大学',
 'Technical University of Berlin',
 '埃默里大学',
 'Emory University',
 '凯斯西储大学',
 'Case Western Reserve University',
 '蒙特雷科技大学',
 'Monterey University of Technology',
 '法赫德法国石油和矿物大学（KFUPM）',
 'Fahd French University of Petroleum and Minerals (KFUPM)',
 '匹兹堡大学',
 'University of Pittsburgh',
 '亚琛工业大学',
 'Aachen University of Technology',
 '博洛尼亚大学',
 'University of Bologna',
 '巴斯大学',
 'University of Bath',
 '德州农工大学',
 'Texas A&M University',
 '巴塞罗那大学',
 'University of Barcelona',
 '韦仕敦大学（西安大略大学）',
 'Weston University (University of Western Ontario)',
 '萨皮恩扎-罗马大学',
 'Sapienza-University of Rome',
 '弗莱堡大学',
 'University of Freiburg',
 '都柏林大学',
 'University of Dublin',
 '佛罗里达大学',
 'University of Florida',
 '哈拉克国立大学',
 'Harak State University',
 '洛桑大学',
 'University of Lausanne',
 '蒂宾根大学',
 'University of Tübingen',
 '印度理工学院孟买分校',
 'Indian Institute of Technology Mumbai',
 '鹿特丹伊拉斯谟大学',
 'Erasmus University Rotterdam',
 '国立清华大学',
 'National Tsinghua University',
 '维也纳技术大学',
 'Vienna University of Technology',
 '哥德堡大学',
 'University of Gothenburg',
 '哈利法大学',
 'Khalifa University',
 '智利大学',
 'University of Chile',
 '印度理工学院德里分校',
 'Indian Institute of Technology Delhi',
 '印度科学研究所班加罗尔',
 'Indian Institute of Science Bangalore',
 '明尼苏达大学',
 'University of Minnesota',
 '法语天主教鲁汶大学',
 'French Catholic University of Leuven',
 '利物浦大学',
 'University of Liverpool',
 '特温特大学',
 'University of Twente',
 '达特茅斯学院',
 'Dartmouth College',
 '马来西亚工艺大学（UTM）',
 'University of Technology Malaysia (UTM)',
 '伍伦贡大学',
 'University of Wollongong',
 '科廷大学',
 'Curtin University',
 '德累斯顿工业大学',
 'Dresden University of Technology',
 '奥塔哥大学',
 'University of Otago',
 '纽卡斯尔大学',
 'Newcastle University',
 '希伯来大学',
 'Hebrew University',
 '卑尔根大学',
 'University of Bergen',
 '麦考瑞大学',
 'Macquarie University'
]

KEYS = [
    ('软件工程','计算机', '网络工程'),
    ('NLP', '机器学习', '深度学习', '自然语言'),
    ('硕士', '研究生'),
    '博士',
    '本科',
    '脑科学',
    '算法',
    'LSTM',
    'Bert',
    'SNN',
    'SLAYER',
    '脉冲神经网络',
    '后端',
    'python',
    'Python',
    'Tensorflow',
    'Pytorch',
    'Nest',
    'Nengo',
    'Lava',
    'Tengine',
    'Loihi',
    '突触',
    '女',
    'k8s',
    'docker',
    '私有云',
    'go',
]


CURRENT_DIR = os.path.dirname(os.path.realpath(__file__))
PHONE_REGEX = re.compile('([1][3-9][0-9]{9})')
COLLEGE = set(COLLEGE_211 + COLLEGE_QS)


def pdftotxt(source_path, text_path):
    with open(source_path, 'rb') as path:
        # 创建一个文档分析器
        parser = PDFParser(path)
        # 创建一个PDF文档对象存储文档结构
        try:
            document =PDFDocument(parser)
        except Exception as e:
            print(source_path, e)
            return
        # 判断文件是否允许文本提取
        if not document.is_extractable:
            raise PDFTextExtractionNotAllowed
        else:
            # 创建一个PDF资源管理器对象来存储资源
            resmag =PDFResourceManager()
            # 设定参数进行分析
            laparams =LAParams()
            # 创建一个PDF设备对象
            # device=PDFDevice(resmag)
            device =PDFPageAggregator(resmag,laparams=laparams)
            # 创建一个PDF解释器对象
            interpreter = PDFPageInterpreter(resmag, device)
            # 处理每一页
            for page in PDFPage.create_pages(document):
                interpreter.process_page(page)
                # 接受该页面的LTPage对象
                layout =device.get_result()
                for y in layout:
                    if(isinstance(y,LTTextBoxHorizontal)):
                        with open(text_path,'a',encoding="utf-8") as f:
                            f.write(y.get_text()+"\n")

def parse_name(s: str):
    n = s.split('.')
    name = n[0].split('-')
    if len(name) > 1:
        n2 = name[-2].strip()
        n1 = name[-1].strip()
        return n2 if '招聘' in n1 else n1
    return ''

def college_valid(text: str):
    for i in COLLEGE:
        if i in text:
            return True
    return False

def main(source_path):
    if not source_path:
        source_path = CURRENT_DIR
    target_dir = os.path.join(CURRENT_DIR, 'tmp')
    if not os.path.exists(target_dir):
        os.mkdir(target_dir)
    target_path = os.path.join(CURRENT_DIR, 'output.csv')
    rs = []
    for filename in os.listdir(source_path):
        path = os.path.join(source_path, filename)
        name = parse_name(filename)
        if not name:
            continue
        text_path = os.path.join(target_dir, '{}.txt'.format(name))
        pdftotxt(path, text_path)
        score = 0
        phone = ''
        with open(text_path, 'r') as f:
            lines = f.readlines()
            lines = ''.join(lines)
            phones = PHONE_REGEX.findall(lines)
            phone = phones[0] if phones else ''
            if college_valid(lines):
                for k in KEYS:
                    if isinstance(k, str):
                        if k in lines:
                            score += 1
                    elif isinstance(k, tuple):
                        for j in k:
                            if j in lines:
                                score += 1
                                break
            rs.append((name, phone, score))
    rs.sort(key=lambda x: x[-1], reverse=True)
    for r in rs:
        if r[-1] > 5:
            print(r[0])
    header = ['name', 'phone', 'score']
    with open(target_path, 'w', encoding='UTF8') as f:
        writer = csv.writer(f)
        writer.writerow(header)
        for r in rs:
            writer.writerow(r)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('-s', '--source_path', default='', help='源文件夹路径')

    args = parser.parse_args()
    main(args.source_path)
